Use RosterDataWarehouse;
-- Sub Querry for Grouping Regions
WITH RegionSubQuery As
(Select
 DistrictName,
 Case
      When DistrictName in ('Masaba', 'Nyamira', 'Sotik') then 'Bensoms'
      When DistrictName in ('Kimilili', 'Matete', 'Saboti', 'Webuye') then 'Elgon'
      When DistrictName in ('Busia', 'Nambale', 'Teso') then 'BorderLand'
	  When DistrictName in ('Hamisi','Kakamega (South)','Vihiga') then 'Haviks'
	  When DistrictName in ('Alego','Gem','Serabo') then 'Yala'
	  When DistrictName in ('Butere','Kakamega B (North)','Mumias') then'Sugar Zone'
	  When DistrictName in ('Imenti','Kenol','Manyatta','Sagana') then'Mount Kenya'
	  When DistrictName in ('Ol Kalou','Njoro') then 'Nakuru'
	  When DistrictName in ('Awendo','Rongo','Ndhiwa','Migori') then 'Lake'
	  When DistrictName in ('Borabu','Gucha','Kisii','Suneka') then 'Kisii'
	  When DistrictName in ('Green Shamba','Nyando','Kabondo','Rachuonyo') then 'Karanya'
	  When DistrictName in ('Belgut','Kapsabet','Kipkelion','Tinderet') then 'KENA'
	  When DistrictName in ('Baharini','Kabiyet','Keiyo') then 'Eldoret'
	  When DistrictName in ('Cherangany','Lugari','Ndalu') then 'Scheme'
	  When DistrictName in ('Bungoma','Chwele','Sirisia') then 'Busitech'
end as Region,
-- Here we are Summing TotalCredit then the other line is for Counting Total Sites
Sum(TotalCredit) As TotalCredit,
COUNT(Distinct DimSiteID) As TotalSites
From v_ClientSalesBizOps
where CountryName = 'Kenya'
and Season = '2022, Long Rain'
and DistrictName not in ('KENYA STAFF', 'OAF Duka')
and PercentRepaid >='0.1'
Group By DistrictName)
-- We now Select the Regions from the Sub Query
Select
Region,
-- To get the Region's Average Credit we now sum the Total Credit Devide by the Sum of Total Sites
    Sum(TotalCredit) / sum(TotalSites) as RegionAvgCredit,
-- Here is the Tier Determination, use this for all the 16 Regions, I have added for only one Region
    Case when Region = 'Bensoms' and Sum(TotalCredit) / sum(TotalSites)  <= 969999 then 1 when Region = 'Bensoms' and Sum(TotalCredit) / sum(TotalSites) > 969999 and  Sum(TotalCredit) / sum(TotalSites) <= 1260999 then 2 when Region = 'Bensoms' and Sum(TotalCredit) / sum(TotalSites) > 1260999 and  Sum(TotalCredit) / sum(TotalSites) <= 1551999 then 3 when Region = 'Bensoms' and Sum(TotalCredit) / sum(TotalSites) > 1551999 and  Sum(TotalCredit) / sum(TotalSites) <= 1939999 then 4 when Region = 'Bensoms' and Sum(TotalCredit) / sum(TotalSites) >= 1940000 then 5
	     When Region = 'BorderLand' and Sum(TotalCredit) / sum(TotalSites)  <= 1329999 then 1 when Region = 'BorderLand' and Sum(TotalCredit) / sum(TotalSites) > 1329999 and  Sum(TotalCredit) / sum(TotalSites) <= 1728999 then 2 when Region = 'BorderLand' and Sum(TotalCredit) / sum(TotalSites) > 1728999 and  Sum(TotalCredit) / sum(TotalSites) <= 2127999 then 3 when Region = 'BorderLand' and Sum(TotalCredit) / sum(TotalSites) > 2127999 and  Sum(TotalCredit) / sum(TotalSites) <= 2659999 then 4 when Region = 'BorderLand' and Sum(TotalCredit) / sum(TotalSites) >= 2660000 then 5
		 when Region = 'Elgon' and Sum(TotalCredit) / sum(TotalSites)  <= 1369999 then 1 when Region = 'Elgon' and Sum(TotalCredit) / sum(TotalSites) > 1369999 and  Sum(TotalCredit) / sum(TotalSites) <= 1780999 then 2 when Region = 'Elgon' and Sum(TotalCredit) / sum(TotalSites) > 1780999 and  Sum(TotalCredit) / sum(TotalSites) <= 2191999 then 3 when Region = 'Elgon' and Sum(TotalCredit) / sum(TotalSites) > 2191999 and  Sum(TotalCredit) / sum(TotalSites) <= 2739999 then 4 when Region = 'Elgon' and Sum(TotalCredit) / sum(TotalSites) >= 2740000 then 5
		 when Region = 'Haviks' and Sum(TotalCredit) / sum(TotalSites)  <= 1199999 then 1 when Region = 'Haviks' and Sum(TotalCredit) / sum(TotalSites) > 1199999 and  Sum(TotalCredit) / sum(TotalSites) <= 1559999 then 2 when Region = 'Haviks' and Sum(TotalCredit) / sum(TotalSites) > 1559999 and  Sum(TotalCredit) / sum(TotalSites) <= 1919999 then 3 when Region = 'Haviks' and Sum(TotalCredit) / sum(TotalSites) > 1919999 and  Sum(TotalCredit) / sum(TotalSites) <= 2399999 then 4 when Region = 'Haviks' and Sum(TotalCredit) / sum(TotalSites) >= 2400000 then 5
		 when Region = 'Yala' and Sum(TotalCredit) / sum(TotalSites)  <= 1549999 then 1 when Region = 'Yala' and Sum(TotalCredit) / sum(TotalSites) > 1549999 and  Sum(TotalCredit) / sum(TotalSites) <= 2014999 then 2 when Region = 'Yala' and Sum(TotalCredit) / sum(TotalSites) > 2014999 and  Sum(TotalCredit) / sum(TotalSites) <= 2479999 then 3 when Region = 'Yala' and Sum(TotalCredit) / sum(TotalSites) > 2479999 and  Sum(TotalCredit) / sum(TotalSites) <= 3099999 then 4 when Region = 'Yala' and Sum(TotalCredit) / sum(TotalSites) >= 3100000 then 5																																																																																																																																																																																																																																																											
		 when Region = 'Sugar Zone' and Sum(TotalCredit) / sum(TotalSites)  <= 1364999 then 1 when Region = 'Sugar Zone' and Sum(TotalCredit) / sum(TotalSites) > 1364999 and  Sum(TotalCredit) / sum(TotalSites) <= 1774499 then 2 when Region = 'Sugar Zone' and Sum(TotalCredit) / sum(TotalSites) > 1774499 and  Sum(TotalCredit) / sum(TotalSites) <= 2183999 then 3 when Region = 'Sugar Zone' and Sum(TotalCredit) / sum(TotalSites) > 2183999 and  Sum(TotalCredit) / sum(TotalSites) <= 2729999 then 4 when Region = 'Sugar Zone' and Sum(TotalCredit) / sum(TotalSites) >= 2730000 then 5																																																																																																																																			
		 when Region = 'Mount Kenya' and Sum(TotalCredit) / sum(TotalSites)  <= 909999 then 1 when Region = 'Mount Kenya' and Sum(TotalCredit) / sum(TotalSites) > 909999 and  Sum(TotalCredit) / sum(TotalSites) <= 1182999 then 2 when Region = 'Mount Kenya' and Sum(TotalCredit) / sum(TotalSites) > 1182999 and  Sum(TotalCredit) / sum(TotalSites) <= 1455999 then 3 when Region = 'Mount Kenya' and Sum(TotalCredit) / sum(TotalSites) > 1455999 and  Sum(TotalCredit) / sum(TotalSites) <= 1819999 then 4 when Region = 'Mount Kenya' and Sum(TotalCredit) / sum(TotalSites) >= 1820000 then 5																										
    	 when Region = 'Nakuru' and Sum(TotalCredit) / sum(TotalSites)  <= 1349999 then 1 when Region = 'Nakuru' and Sum(TotalCredit) / sum(TotalSites) > 1349999 and  Sum(TotalCredit) / sum(TotalSites) <= 1754999 then 2 when Region = 'Yala' and Sum(TotalCredit) / sum(TotalSites) > 1754999 and  Sum(TotalCredit) / sum(TotalSites) <= 2159999 then 3 when Region = 'Nakuru' and Sum(TotalCredit) / sum(TotalSites) > 2159999 and  Sum(TotalCredit) / sum(TotalSites) <= 2699999 then 4 when Region = 'Nakuru' and Sum(TotalCredit) / sum(TotalSites) >= 2700000 then 5																																																																																																																																			
		 when Region = 'Lake' and Sum(TotalCredit) / sum(TotalSites)  <= 1169999 then 1 when Region = 'Lake' and Sum(TotalCredit) / sum(TotalSites) > 1169999 and  Sum(TotalCredit) / sum(TotalSites) <= 1520999 then 2 when Region = 'Lake' and Sum(TotalCredit) / sum(TotalSites) > 1520999 and  Sum(TotalCredit) / sum(TotalSites) <= 1871999 then 3 when Region = 'Lake' and Sum(TotalCredit) / sum(TotalSites) > 1871999 and  Sum(TotalCredit) / sum(TotalSites) <= 2339999 then 4 when Region = 'Lake' and Sum(TotalCredit) / sum(TotalSites) >= 2340000 then 5																																																																																																																				
		 when Region = 'Kisii' and Sum(TotalCredit) / sum(TotalSites)  <= 919999 then 1 when Region = 'Kisii' and Sum(TotalCredit) / sum(TotalSites) > 919999 and  Sum(TotalCredit) / sum(TotalSites) <= 1195999 then 2 when Region = 'Kisii' and Sum(TotalCredit) / sum(TotalSites) > 1195999 and  Sum(TotalCredit) / sum(TotalSites) <= 1471999 then 3 when Region = 'Kisii' and Sum(TotalCredit) / sum(TotalSites) > 1471999 and  Sum(TotalCredit) / sum(TotalSites) <= 1839999 then 4 when Region = 'Kisii' and Sum(TotalCredit) / sum(TotalSites) >= 1840000 then 5																																																																																																																																					
		 when Region = 'Karanya' and Sum(TotalCredit) / sum(TotalSites)  <= 1079999 then 1 when Region = 'Karanya' and Sum(TotalCredit) / sum(TotalSites) > 1079999 and  Sum(TotalCredit) / sum(TotalSites) <= 1403999 then 2 when Region = 'Karanya' and Sum(TotalCredit) / sum(TotalSites) > 1403999 and  Sum(TotalCredit) / sum(TotalSites) <= 1727999 then 3 when Region = 'Karanya' and Sum(TotalCredit) / sum(TotalSites) > 1727999 and  Sum(TotalCredit) / sum(TotalSites) <= 2159999 then 4 when Region = 'Karanya' and Sum(TotalCredit) / sum(TotalSites) >= 2160000 then 5																																																																																																							
	     when Region = 'KENA' and Sum(TotalCredit) / sum(TotalSites)  <= 979999 then 1 when Region = 'KENA' and Sum(TotalCredit) / sum(TotalSites) > 979999 and  Sum(TotalCredit) / sum(TotalSites) <= 1273999 then 2 when Region = 'KENA' and Sum(TotalCredit) / sum(TotalSites) > 1273999 and  Sum(TotalCredit) / sum(TotalSites) <= 1567999 then 3 when Region = 'KENA' and Sum(TotalCredit) / sum(TotalSites) > 1567999 and  Sum(TotalCredit) / sum(TotalSites) <= 1959999 then 4 when Region = 'KENA' and Sum(TotalCredit) / sum(TotalSites) >= 1960000 then 5	
		 when Region = 'Eldoret' and Sum(TotalCredit) / sum(TotalSites)  <= 1619999 then 1 when Region = 'Eldoret' and Sum(TotalCredit) / sum(TotalSites) > 1619999 and  Sum(TotalCredit) / sum(TotalSites) <= 2105999 then 2 when Region = 'Eldoret' and Sum(TotalCredit) / sum(TotalSites) > 2105999 and  Sum(TotalCredit) / sum(TotalSites) <= 2591999 then 3 when Region = 'Eldoret' and Sum(TotalCredit) / sum(TotalSites) > 2591999 and  Sum(TotalCredit) / sum(TotalSites) <= 3239999 then 4 when Region = 'Eldoret' and Sum(TotalCredit) / sum(TotalSites) >= 3240000 then 5																																																																																															
		 when Region = 'Scheme' and Sum(TotalCredit) / sum(TotalSites)  <= 1634999 then 1 when Region = 'Scheme' and Sum(TotalCredit) / sum(TotalSites) > 1634999 and  Sum(TotalCredit) / sum(TotalSites) <= 2125499 then 2 when Region = 'Scheme' and Sum(TotalCredit) / sum(TotalSites) > 2125499 and  Sum(TotalCredit) / sum(TotalSites) <= 2615999 then 3 when Region = 'Scheme' and Sum(TotalCredit) / sum(TotalSites) > 2615999 and  Sum(TotalCredit) / sum(TotalSites) <= 3269999 then 4 when Region = 'Scheme' and Sum(TotalCredit) / sum(TotalSites) >= 3270000 then 5
		 when Region = 'Busitech' and Sum(TotalCredit) / sum(TotalSites)  <= 1249999 then 1 when Region = 'Busitech' and Sum(TotalCredit) / sum(TotalSites) > 1249999 and  Sum(TotalCredit) / sum(TotalSites) <= 1624999 then 2 when Region = 'Busitech' and Sum(TotalCredit) / sum(TotalSites) > 1624999 and  Sum(TotalCredit) / sum(TotalSites) <= 1999999 then 3 when Region = 'Busitech' and Sum(TotalCredit) / sum(TotalSites) > 1999999 and  Sum(TotalCredit) / sum(TotalSites) <= 2499999 then 4 when Region = 'Busitech' and Sum(TotalCredit) / sum(TotalSites) >= 2500000 then 5																																																																																																																																																																																																																																				
																																																																																																																						
	else 0 end as Teir																																																																																															
	  
-- We now group by the Region from the sub query
from RegionSubQuery Group By Region